language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mbarakaja
  password:
    secure: te0d7/NbcUiKXxTqwnTEDWpQdRYJH/vFr6TJ1A4DbHnMl6ZruZJUvZxzikcE4VyQ8dqbMy65gOG10DUTSLHVxFB154QcerZCL2bAEs39Ll4YgWyV/2eI0tGO9qGogaqbAvAwi1FuykwB6ZSBilGPOaOjwg14iW+vgSzItjbw/SujvTfxCh2YQbrCpJhVDVhuXO8yIpaMDC+x8/R2b7oyKlXWpCaVaAhaiJiEuYVoC8yT4lZ9FxYLcF+biw9b06alxWEMqpl1EyJk3t1JZ/DRVmXxVhvnhgKOivKBvcK0EPLXQKjCWRMPC5eGuApCj3RCeBImxGj0N6ZIUblKpk3Wt2lMXrNlXs6swnrj+tj0nHnuOLi4fLzyDfVdzCcpP0lRZZW6Mo/CeOcD/w8kF8qYbZKOoRIsARHeigi8WdAkVllqVq3kZXIBrqVMljqtdFJsEEiX6vGvSvvHT+H/iZ+2dilF7e+2DZDcxK5aOQ55+2k/7vfoQNLyGofdnswrOt9X3CciDlps/7hPwq7j7AarL+qEVAk7UXa/zuB70K4k4zLy/KI8ieHrm0QYpz3fzkJd7Q2uo5q/YMuQO8x/2sbJpZTpW340v9juPS4aqfUWp5g7TD+EZKqIoXv0Kwg6NYkLvxVjansZsFe/wBrIIV/LCpQUDfsE8F+U5Rykt716fEk=
  on:
    tags: true
    repo: mbarakaja/saraki
    python: 3.6
services:
- postgresql
before_script:
- psql -c 'create database test;' -U postgres
env:
- TEST_DATABASE_URI=postgresql://postgres:@localhost/test
